format_version: 1.0.0
name: prometheus
title: Prometheus
version: 0.0.1
license: basic
description: Prometheus Integration
type: integration
categories:
- metrics
requirement:
  kibana:
    versions: ""
screenshots:
- src: img/metricbeat-prometheus-overview.png
  title: Metricbeat Prometheus Overview
  size: 5010x2676
  type: image/png
icons:
- src: img/logo_prometheus.svg
  title: Logo Prometheus
  size: 32x32
  type: image/svg+xml
