id: health
title: Traefik health metrics
release: ga
type: metrics
streams:
- input: traefik/metrics
  vars:
  - default:
    - localhost:8080
    name: hosts
  - default: 10s
    name: period
  title: Traefik health logs
  description: Collect Traefik health metrics
