title: traefik health metrics
release: ga
type: metrics
streams:
- input: traefik/metrics
  vars:
  - name: period
    type: text
    title: Period
    multi: false
    required: true
    show_user: true
    default: 10s
  title: traefik health metrics
  description: Collect traefik health metrics
