- name: traefik.access
  type: group
  fields:
  - name: user_identifier
    type: keyword
  - name: request_count
    type: long
  - name: frontend_name
    type: keyword
  - name: backend_url
    type: keyword
  - name: user_agent
    type: group
    fields:
    - name: device
      type: alias
      path: user_agent.device.name
    - name: name
      type: alias
      path: user_agent.name
    - name: os
      type: alias
      path: user_agent.os.full_name
    - name: os_name
      type: alias
      path: user_agent.os.name
    - name: original
      type: alias
      path: user_agent.original
  - name: geoip
    type: group
    fields:
    - name: continent_name
      type: alias
      path: source.geo.continent_name
    - name: country_iso_code
      type: alias
      path: source.geo.country_iso_code
    - name: location
      type: alias
      path: source.geo.location
    - name: region_name
      type: alias
      path: source.geo.region_name
    - name: city_name
      type: alias
      path: source.geo.city_name
    - name: region_iso_code
      type: alias
      path: source.geo.region_iso_code
