format_version: 1.0.0
name: traefik
title: traefik
version: 0.0.1
license: basic
description: |
  Traefik reverse proxy / load balancer metrics
type: integration
categories:
- logs
- metrics
requirement:
  kibana:
    versions: ""
