{{setEmptyVar input "syslog"}}
{{ ifeq input "syslog" }}
type: syslog
protocol.udp:
  host: "{{defVal syslog.host localhost}}:{{defVal syslog.post 9001}}"


{{ elseifeeq input "file" }}
type: log
paths:
-
  {{!-- If the paths variable is set, it will be used, otherwise falls back to the default config. --}}
  {{ if paths }}
  {{#each path}}
    {{this}}
  {{/each }}
  {{ else }}
    /var/log/iptables.log
  {{/if}
exclude_files: [".gz$"]
{{ /if }}

tags: {{defVal tags "[iptables]"}}

processors:
- add_locale: ~

{{setEmptyVar community_id true}}
{{ if community_id }}
- dissect:
    tokenizer: "%{} SRC=%{source.ip} DST=%{destination.ip} "
    field: "message"
    target_prefix: ""
- dissect:
    tokenizer: "%{} PROTO=%{network.transport} "
    field: "message"
    target_prefix: ""
- if:
    or:
      - equals.network.transport: TCP
      - equals.network.transport: UDP
      - equals.network.transport: SCTP
  then:
    dissect:
      tokenizer: "%{} SPT=%{source.port} DPT=%{destination.port} "
      field: "message"
      target_prefix: ""
  else:
    dissect:
      when:or:
        - equals.network.transport: ICMP
        - equals.network.transport: ICMPv6
      tokenizer: "%{} TYPE=%{iptables.icmp.type} CODE=%{iptables.icmp.code} "
      field: "message"
      target_prefix: ""
- community_id:
    fields:
      icmp_type: iptables.icmp.type
      icmp_code: iptables.icmp.code
{{ end}}
