format_version: 1.0.0
name: traefik
title: Traefik
version: 0.0.1
license: basic
description: Traefik Integration
type: integration
categories:
- logs
- metrics
release: ga
requirement:
  kibana:
    versions: ""
screenshots:
- src: /img/kibana-traefik.png
  title: Kibana Traefik
  size: 1409x1254
  type: image/png
icons:
- src: /img/traefik.svg
  title: Traefik
  size: 340x456
  type: image/svg+xml
datasources:
- name: traefik
  title: Traefik logs and metrics
  description: Collect logs and metrics from Traefik instances
  inputs:
  - type: logs
    description: Collecting logs for Traefik
  - type: traefik/metrics
    description: Collecting metrics for Traefik
