format_version: 1.0.0
name: traefik
title: Traefik
version: 0.0.1
license: basic
description: Traefik Integration
type: integration
categories:
- logs
- metrics
requirement:
  kibana:
    versions: ""
