- description: |
    Metrics obtained from Traefik's health API endpoint
  fields:
  - description: |
      Uptime of Traefik instance in seconds
    name: uptime.sec
    type: long
  - description: |
      Response metrics
    fields:
    - description: |
        Number of responses
      name: count
      type: long
    - description: |
        Average response time in microseconds
      name: avg_time.us
      type: long
    - description: |
        Number of responses per status code
      name: status_codes.*
      object_type: long
      type: object
    name: response
    type: group
  name: traefik.health
  release: ga
  type: group
