title: Traefik access logs
release: ga
type: logs
streams:
- input: logs
  vars:
  - default:
    - /var/log/traefik/access.log*
    multi: true
    name: paths
    os.darwin:
      default:
      - /usr/local/traefik/access.log*
    os.windows:
      default:
      - c:/programdata/traefik/logs/*access.log*
  title: Traefik access logs
  description: Collect Traefik access logs
