title: Traefik access logs
release: ga
type: logs
streams:
- input: logs
  vars:
  - name: paths
    type: text
    title: Paths
    multi: true
    required: true
    show_user: true
    default:
    - /var/log/traefik/access.log*
    os:
      darwin:
        default:
        - /usr/local/traefik/access.log*
      windows:
        default:
        - c:/programdata/traefik/logs/*access.log*
  title: Traefik access logs
  description: Collect Traefik access logs
