id: access
title: Traefik Access Logs
release: ga
type: logs
streams:
- input: logs
  vars:
  - default:
    - /var/log/traefik/access.log*
    name: paths
    os.darwin:
      default:
      - /usr/local/traefik/access.log*
    os.windows:
      default:
      - c:/programdata/traefik/logs/*access.log*
  title: Traefik Access logs
  description: Collect Traefik Access logs
