id: collector
title: Prometheus Collector Metrics
release: ga
type: metrics
streams:
- input: prometheus/metrics
  vars:
  - default:
    - localhost:9090
    name: hosts
  - default: /metrics
    name: metrics_path
  - default: 10s
    name: period
  title: Prometheus Collector logs
  description: Collect Prometheus Collector metrics
