title: Prometheus collector metrics
release: ga
type: metrics
streams:
- input: prometheus/metrics
  vars:
  - name: hosts
    type: text
    title: Hosts
    multi: true
    required: true
    show_user: true
    default:
    - localhost:9090
  - name: metrics_path
    type: text
    title: Metrics Path
    multi: false
    required: true
    show_user: true
    default: /metrics
  - name: period
    type: text
    title: Period
    multi: false
    required: true
    show_user: true
    default: 10s
  title: Prometheus collector metrics
  description: Collect Prometheus collector metrics
