- fields:
  - description: |
      Prometheus metric labels
    name: labels.*
    object_type: keyword
    type: object
  - description: |
      Prometheus metric
    name: metrics.*
    object_type: double
    object_type_mapping_type: '*'
    type: object
  - description: |
      Prometheus value resulted from PromQL
    name: query.*
    object_type: double
    object_type_mapping_type: '*'
    type: object
  name: prometheus
  type: group
